### ISSUE TITLE
XWorkspaces Request

### ISSUE THREAD

**Issue by Qelxiros** [Qelxiros/lazybar#13]
Opening on behalf of @Gh0stGames
> One idea would be adding an example on how to configure xworkspaces to the examples/Cargo.toml file. I've got my workspaces setup but struggling a tiny bit to figure out how to put a gray highlight over the non-empty inactive workspaces, so I can tell where I've got windows at. Just been playing around with it for awhile trying every possible config option to get it to work lol

**Comment by Qelxiros** [comment]
If by highlight you mean background, you might be looking for [`Bg`](https://docs.rs/lazybar-core/latest/lazybar_core/background/enum.Bg.html), although your config looks like you're familiar with that. The specific configuration option here is either `nonempty_attrs = <attrs>` or `inactive_attrs = <attrs>`, where attrs links to the desired background (`Bubble` with `radius = 0` will give you a rectangle). Nonempty workspaces are more common, while inactive workspaces usually only appear as an empty workspace that's visible on another monitor. If you do mean highlight (as in the rectangle along the bottom of the active workspace), they're currently only supported for the active workspace, but I'm working on generalizing them not only to all workspaces, but to all panels. I'll send another message here when that's out.

**Comment by Qelxiros** [comment]
Better support for highlights in xworkspaces has been added in 7f172e2.

**Comment by TheXnlyGhxst** [comment]
Awesome work!

**Comment by Qelxiros** [comment]
Improved highlight functionality and added highlight support for most panels in e1b2d51.
