### ISSUE TITLE
Use `if-addrs` instead of `get_if_addrs`

### ISSUE THREAD

**Issue by 0323pin** [Qelxiros/lazybar#17]
Hi,

I was looking at creating a NetBSD package for `lazybar` and found it depends on `get_if_addrs`.
`get_if_addrs` has been archived back in Nov. 2019 and I would consider it deprecated. Moreover, support for NetBSD was merged post the last release and the crate does not build.

`if_addrs` was forked from `get_if_addrs`, it's actively maintained and contains the necessary code for building on NetBSD, https://github.com/messense/if-addrs

Would it be possible for you to replace the dependency? I could then try packaging `lazybar`, thanks!

**Comment by Qelxiros** [comment]
Fixed in 68cc105. Thanks for letting me know and good luck with packaging! Note that some panels may only work on Linux, so I'd recommend setting feature flags for BSD compilation (I know precisely nothing about NetBSD, so I don't know if that's necessary or feasible).

**Comment by 0323pin** [comment]
Thanks, I'll give it a try.

> I'd recommend setting feature flags for BSD compilation (I know precisely nothing about NetBSD, so I don't know if that's necessary or feasible).

Yes, we can build with whatever features we wish. If, it's necessary, we will see 😃 

I will however, switch off `pulseaudio` locally. I don't have it, even though it's available on NetBSD, I don't want it.
