### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by cecilialau6776** [Qelxiros/lazybar#9]
It would be nice to be able to use images as icons.

**Comment by Qelxiros** [comment]
This seems possible. Some limitations:
- I'll probably only support PNGs (at least at first)
- I probably won't support scaling (at least at first)
- It'll definitely take some config manipulation on your end to make everything look right, but I'll see what I can do to mitigate this.

**Comment by Qelxiros** [comment]
Added in 104ee7b.
